#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/lsm
#
# IDENTIFICATION
#    src/backend/storage/lsm/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/lsm
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS =  \
	lsm.o

include $(top_srcdir)/src/backend/common.mk
