#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/lsmt
#
# IDENTIFICATION
#    src/backend/access/lsmt/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/lsmt
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	lsmtam_handler.o

include $(top_srcdir)/src/backend/common.mk
